# Generated by Django 5.1.6 on 2025-02-24 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kategori',
            new_name='GelirKategori',
        ),
        migrations.CreateModel(
            name='GiderKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('üst_kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finans.giderkategori')),
            ],
        ),
        migrations.AddField(
            model_name='düzenliödeme',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finans.giderkategori'),
        ),
        migrations.AlterField(
            model_name='gider',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finans.giderkategori'),
        ),
    ]
