# Generated by Django 5.1.6 on 2025-02-25 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finans', '0002_rename_kategori_gelirkategori_giderkategori_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='düzenliödemeekstresi',
            name='tarih',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
